FROM ubuntu:20.04
MAINTAINER Daniel Romero-Guzman
LABEL software=BWA-MEM2
ENV version=2.0pre2
ENV version_samtools=1.16.1
ENV version_htslib=1.16
ENV version_bcftools=1.16
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install -y build-essential cmake wget
WORKDIR /usr/local/bin/
RUN apt-get install -y zlib1g-dev libncurses5-dev libncursesw5-dev libbz2-dev liblzma-dev && wget https://github.com/samtools/samtools/releases/download/${version_samtools}/samtools-${version_samtools}.tar.bz2 && tar xvf samtools-${version_samtools}.tar.bz2 && cd samtools-${version_samtools}/ && ./configure && make -j $(nproc) && make install && cd htslib-${version_htslib} && make && make install && export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
WORKDIR /usr/local/bin/
RUN apt-get install -y libcurl4-gnutls-dev && wget https://github.com/samtools/bcftools/releases/download/1.16/bcftools-${version_bcftools}.tar.bz2 && tar xvf bcftools-${version_bcftools}.tar.bz2 && rm bcftools>
WORKDIR /usr/local/bin/
RUN wget https://github.com/bwa-mem2/bwa-mem2/releases/download/v${version}/bwa-mem2-${version}_x64-linux.tar.bz2 && tar jxf bwa-mem2-${version}_x64-linux.tar.bz2 && cp bwa-mem2-${version}_x64-linux/bwa-mem2 bwa-mem2-${version}_x64-linux/bwa-mem2.avx2 bwa-mem2-${version}_x64-linux/bwa-mem2.avx512bw bwa-mem2-${version}_x64-linux/bwa-mem2.sse41 /usr/local/bin
RUN apt-get clean && apt-get purge && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
WORKDIR /home/
