FROM ubuntu:22.04

LABEL maintainer="Daniel Romero-Guzmán <danirg9993@gmail.com>"
LABEL version="STAR_2.7.11b_samtools_1.21_bcftools_1.21"
LABEL description="STAR + samtools + bcftools - RNA-Seq aligner with variant calling utilities"
LABEL source="https://github.com/alexdobin/STAR, https://github.com/samtools/samtools, https://github.com/samtools/bcftools"
LABEL bioinfo.category="aligners"
LABEL bioinfo.subcategory="rna-aligner"

ENV STAR_VERSION=2.7.11b
ENV SAMTOOLS_VERSION=1.21
ENV BCFTOOLS_VERSION=1.21
ENV HTSLIB_VERSION=1.21
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/usr/local/bin:$PATH"

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        git build-essential ca-certificates vim-common \
        zlib1g-dev libgomp1 \
        libbz2-dev liblzma-dev libncurses-dev libcurl4-openssl-dev libssl-dev && \
    # Install STAR
    git clone --branch ${STAR_VERSION} https://github.com/alexdobin/STAR.git /tmp/STAR && \
    cd /tmp/STAR/source && \
    make && \
    cp STAR /usr/local/bin/ && \
    # Install htslib (required for samtools/bcftools)
    git clone --branch ${HTSLIB_VERSION} https://github.com/samtools/htslib.git /tmp/htslib && \
    cd /tmp/htslib && \
    git submodule update --init --recursive && \ 
    make && \
    make install && \
    # Install samtools
    git clone --branch ${SAMTOOLS_VERSION} https://github.com/samtools/samtools.git /tmp/samtools && \
    cd /tmp/samtools && \
    make && \
    make install && \
    # Install bcftools
    git clone --branch ${BCFTOOLS_VERSION} https://github.com/samtools/bcftools.git /tmp/bcftools && \
    cd /tmp/bcftools && \
    make && \
    make install && \
    # Clean
    apt-get purge -y git build-essential ca-certificates vim-common && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /root/.cache

WORKDIR /data

ENTRYPOINT ["bash"]