FROM ubuntu:20.04
MAINTAINER Daniel Romero-Guzman
LABEL software=BWA
LABEL GIT=https://github.com/lh3/bwa
LABEL manual=https://bio-bwa.sourceforge.net/bwa.shtml
ENV version=0.7.17
ENV version_samtools=1.16.1
ENV version_htslib=1.16
ENV version_bcftools=1.6
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install -y build-essential cmake git wget
WORKDIR /usr/local/bin/
RUN apt-get install -y zlib1g-dev libncurses5-dev libncursesw5-dev libbz2-dev liblzma-dev && wget https://github.com/samtools/samtools/releases/download/${version_samtools}/samtools-${version_samtools}.tar.bz2 && tar xvf samtools-${version_samtools}.tar.bz2 && rm samtools-${version_samtools}.tar.bz2 && cd samtools-${version_samtools}/ && ./configure && make -j $(nproc) && make install && cd htslib-${version_htslib} && make && make install && export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
WORKDIR /usr/local/bin/
RUN apt-get install -y libcurl4-gnutls-dev && wget https://github.com/samtools/bcftools/releases/download/1.16/bcftools-${version_bcftools}.tar.bz2 && tar xvf bcftools-${version_bcftools}.tar.bz2 && rm bcftools-${version_bcftools}.tar.bz2 && cd bcftools-${version_bcftools}/ && ./configure && make -j $(nproc) && make install
WORKDIR /usr/local/bin/
RUN git clone https://github.com/lh3/bwa.git && mv bwa bwa_git && cd bwa_git && make -j $(nproc) && cp bwa qualfa2fq.pl xa2multi.pl /usr/local/bin
RUN apt-get clean && apt-get purge && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
WORKDIR /home/
